language: clojure
lein: 2.9.1
dist: trusty
script: lein do clean, javac, test :all

# Cache our Maven deps to be kind to clojars, github, docker images
cache:
    directories:
    - $HOME/bin
    - $HOME/.m2

notifications:
  email: false
